C:\Users\msi\Desktop\ECE-228\Project\latent_ode_ece_228
run_models.py --n 10000 --niters 100 --lr 0.01 --batch_size 50 --viz False --save experiments/ --random_seed 1991 --dataset hopper --latent_ode False --classic_rnn False --ode_rnn True--z0_encoder odernn --latents 15 --rec_dims 30 --rec_layers 3 --gen_layers 3 --units 300 --gru_units 100 --timepoints 100 --max_t 5.0 --noise_weight 0.01 --extrap False 
MUJOCO_GL is not set, so an OpenGL backend will be chosen automatically.
Successfully imported OpenGL backend: glfw
MuJoCo library version is: 3.1.5
c:\Users\msi\anaconda3\envs\py310\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:123: UserWarning: Warning: in file pred_render_25_0.5_ODE_RNN/predicted.mp4, 921600 bytes wanted but 0 bytes read,at frame 100/101, at time 6.67/6.67 sec. Using the last valid frame instead.
  warnings.warn("Warning: in file %s, "%(self.filename)+

c:\Users\msi\anaconda3\envs\py310\lib\site-packages\torchdiffeq\_impl\misc.py:296: UserWarning: t is not on the same device as y0. Coercing to y0.device.
  warnings.warn("t is not on the same device as y0. Coercing to y0.device.")

